---
apiVersion: v1
kind: Namespace
metadata:
  name: hello-world
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: hello-world
  name: dep-hello-world
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: app-hello-world
  replicas: 3
  template:
    metadata:
      labels:
        app.kubernetes.io/name: app-hello-world
    spec:
      containers:
      - image: 659702723394.dkr.ecr.cn-northwest-1.amazonaws.com.cn/jerrytest/application/go-hello-world:<VERSION>
        imagePullPolicy: Always
        name: app-hello-world
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  namespace: hello-world
  name: ser-hello-world
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  type: NodePort
  selector:
    app.kubernetes.io/name: app-hello-world
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  namespace: hello-world
  name: ing-hello-world
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
spec:
  rules:
    - http:
        paths:
          - path: /*
            backend:
              serviceName: ser-hello-world
              servicePort: 8080              
